# Generated by Django 5.0.4 on 2024-05-12 19:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CountryCodes",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("country", models.CharField(max_length=255, verbose_name="Страна")),
                ("currency", models.CharField(max_length=255, verbose_name="Валюта")),
                ("code", models.CharField(max_length=255, verbose_name="Код")),
                ("number", models.CharField(max_length=255, verbose_name="Номер")),
            ],
        ),
        migrations.CreateModel(
            name="CurrencyRates",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "usd_currency",
                    models.CharField(max_length=255, verbose_name="Доллар США"),
                ),
                ("eur_currency", models.CharField(max_length=255, verbose_name="Евро")),
                (
                    "gpb_currency",
                    models.CharField(max_length=255, verbose_name="Фунт стерлингов"),
                ),
                (
                    "ikr_currency",
                    models.CharField(max_length=255, verbose_name="Индийская рупия"),
                ),
                (
                    "cny_currency",
                    models.CharField(
                        max_length=255, verbose_name="Китайский юань Жэньминьби"
                    ),
                ),
                (
                    "try_currency",
                    models.CharField(max_length=255, verbose_name="Турецкая лира"),
                ),
                (
                    "jpy_currency",
                    models.CharField(max_length=255, verbose_name="Японская йена"),
                ),
                ("date", models.DateField(verbose_name="Дата")),
            ],
        ),
        migrations.CreateModel(
            name="CurrencyRateChange",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(verbose_name="Дата")),
                (
                    "relative_change",
                    models.FloatField(verbose_name="Относительное изменение (%)"),
                ),
                (
                    "currency",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="currencies_by_country.countrycodes",
                        verbose_name="Валюта",
                    ),
                ),
            ],
        ),
    ]
