# Generated by Django 5.0.4 on 2024-05-13 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("currencies_by_country", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="currencyratechange",
            name="currency",
            field=models.CharField(max_length=255, verbose_name="Валюта"),
        ),
    ]
